version: "3"

postgres:
  image: postgres:12.2
  environment:
    - POSTGRES_PASSWORD=
  volumes:
    - /postgres:/var/lib/postgresql/data

web-server:
  build: ./packages/web-server
  image: visi/web-server
  restart: always
  env_file: .env
  ports:
    - "3000:3000"
  depends_on:
    - postgres
  volumes:
    - ./logs:./logs

# Uncomment if you want to deploy frontend thru Docker
# web-client:
#   build: ./packages/web-client
#   image: visi/web-client
#   restart: always
#   env_file: .env
#   ports:
#     - "4000:3000"
