version: '3'

services:
  postgres:
    image: postgres:12.2
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web-server:
    build:
      context: .
      dockerfile: ./packages/web-server/Dockerfile
    image: visiblehq/web-server
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./logs:/home/logs

  web-client:
    build:
      context: .
      dockerfile: ./packages/web-client/Dockerfile
    image: visiblehq/web-client
    restart: always
    env_file: .env
    ports:
      - '4000:4000'
