version: '3'

services:
  web:
    build: .
    image: visiblehq/web
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
      - '4000:4000'
    depends_on:
      - postgres
    volumes:
      - ./logs:/home/packages/web-server/logs

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: visible
      POSTGRES_PASSWORD: visible
    volumes:
      - ./postgres:/var/lib/postgresql/data
